### ISSUE TITLE
OverflowError: cannot convert float infinity to integer

### ISSUE THREAD

**Issue by aa-gamJain** [ranaroussi/quantstats#6]
[test.xlsx](https://github.com/ranaroussi/quantstats/files/3463726/test.xlsx)
Below two functions are not working in attached data.

1. qs.plots.snapshot()
2. qs.reports.full()

Function returns:
OverflowError: cannot convert float infinity to integer

**Comment by ranaroussi** [comment]
Try cleaning up your data before using it, using:

```python
import numpy as np
import quantstats as qs

your_data = your_data.replace([np.inf, -np.inf, -0], 0)

qs.plots.snapshot(your_data)
```

Let me know if that works out 😉

**Comment by aa-gamJain** [comment]
Not worked

**Comment by ranaroussi** [comment]
Can you re-upload your data? I seem to be corrupted...

**Comment by aa-gamJain** [comment]
https://drive.google.com/open?id=1XN3wfOiFFGVJop6SkephKzUeUKjhqK6H

**Comment by ranaroussi** [comment]
Upgrade to the latest version and try again.

```
$ pip install quantstats -U --no-cache-dir
```

**Comment by aa-gamJain** [comment]
Still same error

**Comment by ranaroussi** [comment]
Running this code works ok for me:

```python

import pandas as pd
import quantstats as qs

df = pd.read_csv('test.csv', names=['date', 'price'], index_col=['date'], parse_dates=['date'])[100:]
df['returns'] = df['price'].pct_change().fillna(0)

qs.plots.snapshot(df['returns'])
```

Result is below:
<img width="714" alt="Unknown" src="https://user-images.githubusercontent.com/1185458/62411527-e206e700-b5fc-11e9-9b1c-6ea753b4ac81.png">

**Comment by ranaroussi** [comment]
If you're using jupyter - try reloading retarting the notebook kernel and import the libraries again to make sure you're using the latest version.

**Comment by aa-gamJain** [comment]
Not working in: `qs.reports.full()`

**Comment by ranaroussi** [comment]
Can you post the entire code you're using? I've tested every method and eveything works.

**Comment by aa-gamJain** [comment]
`df = pd.read_csv('test.csv', names=['date', 'price'], index_col=['date'], parse_dates=['date'])[100:]
df['returns'] = df['price'].pct_change().fillna(0)

qs.plots.snapshot(df['returns'])   # Works

qs.reports.full(df['returns'] , "SPY")  # return error`

ValueError: cannot convert float NaN to integer

**Comment by aa-gamJain** [comment]
![image](https://user-images.githubusercontent.com/22656341/62412007-8860e580-b619-11e9-8b15-c47238af7db5.png)

Can you share which version of pandas and numpy are you using?

If you check the picture it won't able to plot Rolling Beta to Benchmark

**Comment by ranaroussi** [comment]
Upgrade to the latest version and try again. Again :)

$ pip install quantstats -U --no-cache-dir

**Comment by aa-gamJain** [comment]
I upgraded again. Restart the jupyter notebook and still the same error.

By error it looks there is some error in ` plot_rolling_beta`

**Comment by aa-gamJain** [comment]
mmin = min([-100, int(beta.min()*100)])
In this line beta.min() returning NaN so it cannot convert NaN to integer. Can you please check?

**Comment by ranaroussi** [comment]
The latest version doesn’t return NaNs but rather zeros.

Are you 100% sure you’re using version 0.0.20?

Run `qs.__version__`. What do you get?


On 3 Aug 2019, at 15:46, Aagam Jain <notifications@github.com> wrote:

mmin = min([-100, int(beta.min()*100)])
In this line beta.min() returning NaN so it cannot convert NaN to integer.
Can you please check?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/ranaroussi/quantstats/issues/6?email_source=notifications&email_token=AAJBNMQBGY7X3ULUFCCP25TQCV4YZA5CNFSM4IJCYXB2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD3PN2SI#issuecomment-517922121>,
or mute the thread

**Comment by aa-gamJain** [comment]
I run the pip install quantstats -U --no-cache-dir

still its 0.0.19

**Comment by aa-gamJain** [comment]
I fixed it out. Thank you very much :)

**Comment by ranaroussi** [comment]
👍🏻

**Comment by ranaroussi** [comment]
👍🏻

**Comment by Onepamopa** [comment]
BTW, the error still occurs, I'm investigating further and will provide more details when I have them.

**Comment by chenyiworld** [comment]
encountering the same issue. Can kindly explain how you resolved it? thanks
